### ISSUE TITLE
- erreur socket hanged up.

### ISSUE THREAD

**Issue by zCrin** [zCrin/pratos#1]
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zCrin** [comment]
Résultats de la recherche d’erreur : 
- ne provient pas des recipes (conditions)
- ne provient pas des plugins
- ne provient pas de socket.io
- ne provient pas de HTTPS

**Comment by zCrin** [comment]
Origine trouvée : utilisation de bodyparser() et node-proxy impossible

**Comment by zCrin** [comment]
Trouble in http.get callback. Fixed 
![GitHub issue state](https://img.shields.io/github/issues/detail/s/zCrin/pratos/1.svg)
